const actionTypes = {
    TABLE_LOADING: "TABLE_LOADING",
    DELETE_DISABLED: "DELETE_DISABLED",
    DELETE_SHOW: "DELETE_SHOW",
    DETAIL_SHOW: "DETAIL_SHOW",
    LIST_DATA: "LIST_DATA",
    COPY_DATA: "COPY_DATA",
    COLUMN: "COLUMN",
    SELECTED_SIZE: "SELECTED_SIZE",
    SELECTED_ITEM: "SELECTED_ITEM",
    APPROVE_ITEM: "APPROVE_ITEM",
    REJECT_ITEM: "REJECT_ITEM",
    APPROVE_DISABLED: "APPROVE_DISABLED",
    REJECT_DISABLED: "REJECT_DISABLED",
    SHOW_APPROVE: "SHOW_APPROVE",
    SHOW_REJECT: "SHOW_REJECT",
    CURRENT_PAGE: "CURRENT_PAGE",
    PAGE_SIZE: "PAGE_SIZE"
}
export default actionTypes