const actionTypes = {
    TABLE_LOADING: "TABLE_LOADING",
    DOWNLOAD_DISABLED: "DOWNLOAD_DISABLED",
    DOWNLOADALL_DISABLED: "DOWNLOADALL_DISABLED",
    DELETE_SHOW: "DELETE_SHOW",
    DETAIL_SHOW: "DETAIL_SHOW",
    LOADING_SHOW: "LOADING_SHOW",
    LIST_DATA: "LIST_DATA",
    COLUMN: "COLUMN",
    SELECTED_SIZE: "SELECTED_SIZE",
    SELECTED_ITEM: "SELECTED_ITEM",
    CURRENT_PAGE: "CURRENT_PAGE",
    PAGE_SIZE: "PAGE_SIZE",
    TABLE_DETAIL: "TABLE_DETAIL"
}
export default actionTypes