const actionTypes = {
    TABLE_LOADING:"TABLE_LOADING",
    DELETE_DISABLED: "DELETE_DISABLED",
    EDIT_DISABLED: "EDIT_DISABLED",
    DELETE_SHOW: "DELETE_SHOW",
    DETAIL_SHOW: "DETAIL_SHOW",
    LOADING_SHOW: "LOADING_SHOW",
    LIST_DATA: "LIST_DATA",
    COLUMN: "COLUMN",
    SELECTED_SIZE: "SELECTED_SIZE",
    SELECTED_ITEM: "SELECTED_ITEM",
    CURRENT_PAGE: "CURRENT_PAGE",
    PAGE_SIZE: "PAGE_SIZE",
    STOP_DISABLED: "STOP_DISABLED",
    PAUSE_DISABLED: "PAUSE_DISABLED",
    START_DISABLED: "START_DISABLED",
    SHOW_STOP: "SHOW_STOP",
    SHOW_PAUSE: "SHOW_PAUSE",
    SHOW_START: "SHOW_START"
}
export default actionTypes