const actionTypes = {
    TABLE_LOADING:"TABLE_LOADING",
    DELETE_DISABLED: "DELETE_DISABLED",
    EDIT_DISABLED: "EDIT_DISABLED",
    DELETE_SHOW: "DELETE_SHOW",
    DETAIL_SHOW: "DETAIL_SHOW",
    LOADING_SHOW: "LOADING_SHOW",
    LIST_DATA: "LIST_DATA",
    COLUMN: "COLUMN",
    SELECTED_SIZE: "SELECTED_SIZE",
    SELECTED_ITEM: "SELECTED_ITEM",
    IMPORT_SHOW: "IMPORT_SHOW",
    UPLOADING: "UPLOADING",
    FILE_LIST:"FILE_LIST",
    CURRENT_PAGE: "CURRENT_PAGE",
    PAGE_SIZE: "PAGE_SIZE"
}
export default actionTypes