const actionTypes = {
    TABLE_LOADING: "TABLE_LOADING",
    KICKOFF_DISABLED: "KICKOFF_DISABLED",
    DELETE_SHOW: "DELETE_SHOW",
    DETAIL_SHOW: "DETAIL_SHOW",
    LOADING_SHOW: "LOADING_SHOW",
    LIST_DATA: "LIST_DATA",
    COLUMN: "COLUMN",
    SELECTED_SIZE: "SELECTED_SIZE",
    SELECTED_ITEM: "SELECTED_ITEM",
    KICK_OFF: "KICK_OFF",
    CURRENT_PAGE: "CURRENT_PAGE",
    PAGE_SIZE: "PAGE_SIZE"
}
export default actionTypes